### ISSUE TITLE
Issue with creating Leap_initialize

### ISSUE THREAD

**Issue by jbartolozzi** [arqtiq/HouLEAP#1]
I am running this on MacOS

I am able to run `import Leap` from houdini by following the instructions here:
https://stackoverflow.com/questions/42401156/leap-motion-error-fatal-python-error-pythreadstate-get-no-current-thread-abor
`install_name_tool -change /Library/Frameworks/Python.framework/Versions/2.7/Python /Applications/Houdini/Houdini16.5.571/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib LeapPython.so`

When I hit tab and try to create a LEAP_Initialize node, I can see it in the tab menu, but nothing shows up when I hit enter.

If I manually install and create the HDA, I get the following error, which I assume is an issue with `hou.session.leap`

```
Error | Invalid source /obj/geo1/LEAP_Initialize1/python1Error: Python error: Traceback (most recent call last):File "", line 11, in NameError: name 'leap' is not defined.
-- | --
```

Any ideas? I'd love to be able to get this working. Thanks

**Comment by jbartolozzi** [comment]
Which SDK version did you use to develop the plugin?
Thanks

**Comment by arqtiq** [comment]
Never tried on MacOS sorry
you'll need to copy the SDL binaries to /scripts/python  I justs copied the ones for Windows

Have you tried to open the example hip file ?
It works under Houdini 17 too

**Comment by arqtiq** [comment]
LEAP_Initialize node fixed
